name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          composer install
          npm run build

      - name: Remove unused composer library.
        run: |
          cd vendor/google/apiclient-services/src/Google/Service/
          ls | grep -v -E 'Sheets|Sheets.php$' | xargs rm -r

      - name: Run unit test
        run: |
          npm run test:unit

      # run the wp-env setup command (wp-env start)
      - name: setup wp env
        run: |
          npx wp-env start

      - name: Run E2E test
        run: |
          npm run test:e2e
