name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tag:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          composer install
          npm run build
      - name: Remove unused composer library.
        run: |
          cd vendor/google/apiclient-services/src/Google/Service/
          ls | grep -v -E 'Sheets|Sheets.php$' | xargs rm -r
      - name: Run unit test
        run: npm run test:unit
      - name: Run E2E test
        run: npm run test:e2e
