name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New tag

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Composer Install
        uses: php-actions/composer@v1
        with:
          args: install

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.1.0'

      - name: Build
        run: |
          npm install
          npm run build

      - name: Get tag version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: Update plugin version
        run: ./tools/bin/create-release.sh $RELEASE_VERSION
      - name: Update README.md from readme.txt
        run: npx grunt
      - name: Push readme.txt etc to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "naogify"
          git config --global user.email "n.globe.us@gmail.com"
          git remote set-url origin https://naogify:${GITHUB_TOKEN}@github.com/naogify/wp-simple-spreadsheet-fetcher-for-google.git
          git checkout -b master
          git add .
          git commit -m"Update Version"
          git push origin master
      - name: Remove unused composer library.
        run: |
          cd vendor/google/apiclient-services/src/Google/Service/
          ls | grep -v -E 'Sheets|Sheets.php$' | xargs rm -r
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
